gallery/urls.py
from django.urls import path, re_path

from . import views

app_name = "gallery"
urlpatterns = [
    re_path(r"^delete/(?P<pk>\d+)/$", views.delete, name="delete"),
    path("", views.index, name="index"),
]

gallerysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("gallery.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models
# from storages.backends.azure_storage import AzureStorage


class Post(models.Model):
    # image = models.ImageField(storage=AzureStorage())
    image = models.ImageField(upload_to='images/')
    title = models.CharField(max_length=200)
    description = models.TextField()
    pub_date = models.DateTimeField()

gallery/forms.py
from django import forms

from gallery.models import Post


class PostForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={"rows": 3}))

    class Meta:
        model = Post
        fields = ["image", "title", "description"]

gallery/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from gallery.forms import PostForm
from gallery.models import Post


def index(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.clean()
            Post(
                image=form.cleaned_data["image"],
                title=form.cleaned_data["title"],
                description=form.cleaned_data["description"],
                pub_date=timezone.now()
            ).save()
            return redirect("/")
    else:
        form = PostForm()

    context = {
        "posts": Post.objects.all().order_by("pub_date").reverse(),
        "form": form
    }
    return render(request, "index.html", context)


def delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        post.image.delete()
        post.delete()
    return redirect("/")

templates/index.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <title>Gallery</title>
</head>

<body>
<div class="container">
    <h1>Gallery</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">
            Submit
        </button>
    </form>

    <div class="row row-cols-md-3">
        {% for post in posts %}
            <div class="col-md">
                <div class="card h-100">
                    <img class="card-img-top" src="{{ post.image.url }}" alt="{{ post.title }}">
                    <div class="card-body border-top border-3">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text">{{ post.description }}</p>
                    </div>
                    <div class="card-footer">
                        <form action="{% url 'gallery:delete' post.id %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-danger w-100 h-100" type="submit">
                                Delete
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
</body>
</html>